version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./data:/app/data

volumes:
  postgres_data:

networks:
  glossary-network:
    driver: bridge 